from __future__ import annotations

from typing import Protocol

from .domain import RobotState, VelocityCommand


class RobotPort(Protocol):
    def connect(self) -> None: ...
    def read_state(self) -> RobotState: ...
    def command_velocity(self, command: VelocityCommand) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...

